/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Principal;

import gui.Alterar.AlterarBebida;
import gui.Alterar.AlterarCliente;
import gui.Alterar.AlterarComida;
import gui.Alterar.AlterarNotaFiscal;
import gui.Alterar.AlterarVendedor;
import gui.Cadastro.CadastroBebida;
import gui.Cadastro.CadastroCliente;
import gui.Cadastro.CadastroComida;
import gui.Cadastro.CadastroNotaFiscal;
import gui.Cadastro.CadastroVendedor;
import gui.Consultar.ConsultarBebida;
import gui.Consultar.ConsultarCliente;
import gui.Consultar.ConsultarComida;
import gui.Consultar.ConsultarNotaFiscal;
import gui.Consultar.ConsultarVendedor;
import gui.Deletar.DeletarBebida;
import gui.Deletar.DeletarCliente;
import gui.Deletar.DeletarComida;
import gui.Deletar.DeletarNotaFiscal;
import gui.Deletar.DeletarVendedor;

/**
 *
 * @author thade
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBarMenuPrincipal = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroCliente = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroVendedor = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroCardapio = new javax.swing.JMenu();
        jMenuItemCadastroBebida = new javax.swing.JMenuItem();
        jMenuItemCadastrarComida = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCadastroNotaFiscal = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuAlterar = new javax.swing.JMenu();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlterarCliente = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlterarVendedor = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroCardapio1 = new javax.swing.JMenu();
        jMenuItemAlterarBebida = new javax.swing.JMenuItem();
        jMenuItemAlterarComida = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAlterarNotaFiscal = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuDeletar = new javax.swing.JMenu();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDeletarCliente = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDeletarVendedor = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroCardapio2 = new javax.swing.JMenu();
        jMenuItemDeletarBebida = new javax.swing.JMenuItem();
        jMenuDeletarComida = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDeletarNotaFiscal = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuConsultar = new javax.swing.JMenu();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsultarCliente = new javax.swing.JMenuItem();
        jSeparator17 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsultarVendedor = new javax.swing.JMenuItem();
        jSeparator18 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroCardapio3 = new javax.swing.JMenu();
        jMenuItemConsultarBebida = new javax.swing.JMenuItem();
        jMenuItemConsultarComida = new javax.swing.JMenuItem();
        jSeparator19 = new javax.swing.JPopupMenu.Separator();
        jMenuItemConsultarNotaFiscal = new javax.swing.JMenuItem();
        jSeparator20 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setName("Menu Principal"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Selecione acima o que deseja fazer");

        jMenuCadastro.setText("Cadastrar");
        jMenuCadastro.add(jSeparator12);

        jMenuItemCadastroCliente.setText("Cliente");
        jMenuItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroCliente);
        jMenuCadastro.add(jSeparator3);

        jMenuItemCadastroVendedor.setText("Vendedor");
        jMenuItemCadastroVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroVendedorActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroVendedor);
        jMenuCadastro.add(jSeparator2);

        jMenuCadastroCardapio.setText("Produto");

        jMenuItemCadastroBebida.setText("Bebida");
        jMenuItemCadastroBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroBebidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio.add(jMenuItemCadastroBebida);

        jMenuItemCadastrarComida.setText("Comida");
        jMenuItemCadastrarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarComidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio.add(jMenuItemCadastrarComida);

        jMenuCadastro.add(jMenuCadastroCardapio);
        jMenuCadastro.add(jSeparator1);

        jMenuItemCadastroNotaFiscal.setText("Nota Fiscal");
        jMenuItemCadastroNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroNotaFiscalActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadastroNotaFiscal);
        jMenuCadastro.add(jSeparator13);

        jMenuBarMenuPrincipal.add(jMenuCadastro);

        jMenuAlterar.setText("Alterar");
        jMenuAlterar.add(jSeparator14);

        jMenuItemAlterarCliente.setText("Cliente");
        jMenuItemAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarClienteActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarCliente);
        jMenuAlterar.add(jSeparator4);

        jMenuItemAlterarVendedor.setText("Vendedor");
        jMenuItemAlterarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarVendedorActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarVendedor);
        jMenuAlterar.add(jSeparator5);

        jMenuCadastroCardapio1.setText("Produto");

        jMenuItemAlterarBebida.setText("Bebida");
        jMenuItemAlterarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarBebidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio1.add(jMenuItemAlterarBebida);

        jMenuItemAlterarComida.setText("Comida");
        jMenuItemAlterarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarComidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio1.add(jMenuItemAlterarComida);

        jMenuAlterar.add(jMenuCadastroCardapio1);
        jMenuAlterar.add(jSeparator6);

        jMenuItemAlterarNotaFiscal.setText("Nota Fiscal");
        jMenuItemAlterarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarNotaFiscalActionPerformed(evt);
            }
        });
        jMenuAlterar.add(jMenuItemAlterarNotaFiscal);
        jMenuAlterar.add(jSeparator15);

        jMenuBarMenuPrincipal.add(jMenuAlterar);

        jMenuDeletar.setText("Deletar");
        jMenuDeletar.add(jSeparator10);

        jMenuItemDeletarCliente.setText("Cliente");
        jMenuItemDeletarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarClienteActionPerformed(evt);
            }
        });
        jMenuDeletar.add(jMenuItemDeletarCliente);
        jMenuDeletar.add(jSeparator7);

        jMenuItemDeletarVendedor.setText("Vendedor");
        jMenuItemDeletarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarVendedorActionPerformed(evt);
            }
        });
        jMenuDeletar.add(jMenuItemDeletarVendedor);
        jMenuDeletar.add(jSeparator8);

        jMenuCadastroCardapio2.setText("Produto");

        jMenuItemDeletarBebida.setText("Bebida");
        jMenuItemDeletarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarBebidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio2.add(jMenuItemDeletarBebida);

        jMenuDeletarComida.setText("Comida");
        jMenuDeletarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDeletarComidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio2.add(jMenuDeletarComida);

        jMenuDeletar.add(jMenuCadastroCardapio2);
        jMenuDeletar.add(jSeparator9);

        jMenuItemDeletarNotaFiscal.setText("Nota Fiscal");
        jMenuItemDeletarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeletarNotaFiscalActionPerformed(evt);
            }
        });
        jMenuDeletar.add(jMenuItemDeletarNotaFiscal);
        jMenuDeletar.add(jSeparator11);

        jMenuBarMenuPrincipal.add(jMenuDeletar);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.add(jSeparator16);

        jMenuItemConsultarCliente.setText("Cliente");
        jMenuItemConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarClienteActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarCliente);
        jMenuConsultar.add(jSeparator17);

        jMenuItemConsultarVendedor.setText("Vendedor");
        jMenuItemConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarVendedorActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarVendedor);
        jMenuConsultar.add(jSeparator18);

        jMenuCadastroCardapio3.setText("Produto");

        jMenuItemConsultarBebida.setText("Bebida");
        jMenuItemConsultarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarBebidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio3.add(jMenuItemConsultarBebida);

        jMenuItemConsultarComida.setText("Comida");
        jMenuItemConsultarComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarComidaActionPerformed(evt);
            }
        });
        jMenuCadastroCardapio3.add(jMenuItemConsultarComida);

        jMenuConsultar.add(jMenuCadastroCardapio3);
        jMenuConsultar.add(jSeparator19);

        jMenuItemConsultarNotaFiscal.setText("Nota Fiscal");
        jMenuItemConsultarNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConsultarNotaFiscalActionPerformed(evt);
            }
        });
        jMenuConsultar.add(jMenuItemConsultarNotaFiscal);
        jMenuConsultar.add(jSeparator20);

        jMenuBarMenuPrincipal.add(jMenuConsultar);

        setJMenuBar(jMenuBarMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarClienteActionPerformed
        AlterarCliente cliAlterar = new AlterarCliente();
        cliAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarClienteActionPerformed

    private void jMenuItemDeletarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarClienteActionPerformed
        DeletarCliente cliDelete = new DeletarCliente();
        cliDelete.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeletarClienteActionPerformed

    private void jMenuItemConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarClienteActionPerformed
        ConsultarCliente cliConsultar = new ConsultarCliente();
        cliConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarClienteActionPerformed

    private void jMenuItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroClienteActionPerformed
        CadastroCliente cliCadastro = new CadastroCliente();
        cliCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroClienteActionPerformed

    private void jMenuItemCadastroBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroBebidaActionPerformed
        CadastroBebida bebCadastro = new CadastroBebida();
        bebCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroBebidaActionPerformed

    private void jMenuItemCadastroVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroVendedorActionPerformed
        CadastroVendedor vendCadastro = new CadastroVendedor();
        vendCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroVendedorActionPerformed

    private void jMenuItemAlterarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarBebidaActionPerformed
        AlterarBebida bebAlterar = new AlterarBebida();
        bebAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarBebidaActionPerformed

    private void jMenuItemDeletarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarBebidaActionPerformed
        DeletarBebida bebAlterar = new DeletarBebida();
        bebAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeletarBebidaActionPerformed

    private void jMenuItemConsultarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarBebidaActionPerformed
        ConsultarBebida bebConsultar = new ConsultarBebida();
        bebConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarBebidaActionPerformed

    private void jMenuItemCadastrarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarComidaActionPerformed
        CadastroComida comCadastrar = new CadastroComida();
        comCadastrar.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarComidaActionPerformed

    private void jMenuItemCadastroNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroNotaFiscalActionPerformed
        CadastroNotaFiscal notaFiscalCadastro = new CadastroNotaFiscal();
        notaFiscalCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroNotaFiscalActionPerformed

    private void jMenuItemAlterarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarVendedorActionPerformed
        AlterarVendedor vendAlterar = new AlterarVendedor();
        vendAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarVendedorActionPerformed

    private void jMenuItemAlterarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarComidaActionPerformed
        AlterarComida comAlterar = new AlterarComida();
        comAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarComidaActionPerformed

    private void jMenuItemAlterarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarNotaFiscalActionPerformed
        AlterarNotaFiscal notaFiscalAlterar = new AlterarNotaFiscal();
        notaFiscalAlterar.setVisible(true);
    }//GEN-LAST:event_jMenuItemAlterarNotaFiscalActionPerformed

    private void jMenuItemDeletarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarVendedorActionPerformed
        DeletarVendedor vendDeletar = new DeletarVendedor();
        vendDeletar.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeletarVendedorActionPerformed

    private void jMenuDeletarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDeletarComidaActionPerformed
        DeletarComida vendComida = new DeletarComida();
        vendComida.setVisible(true);
    }//GEN-LAST:event_jMenuDeletarComidaActionPerformed

    private void jMenuItemDeletarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeletarNotaFiscalActionPerformed
        DeletarNotaFiscal notaFiscalDeletar = new DeletarNotaFiscal();
        notaFiscalDeletar.setVisible(true);
    }//GEN-LAST:event_jMenuItemDeletarNotaFiscalActionPerformed

    private void jMenuItemConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarVendedorActionPerformed
        ConsultarVendedor vendConsultar = new ConsultarVendedor();
        vendConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarVendedorActionPerformed

    private void jMenuItemConsultarComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarComidaActionPerformed
        ConsultarComida comConsultar = new ConsultarComida();
        comConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarComidaActionPerformed

    private void jMenuItemConsultarNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsultarNotaFiscalActionPerformed
        ConsultarNotaFiscal notaFiscalConsultar = new ConsultarNotaFiscal();
        notaFiscalConsultar.setVisible(true);
    }//GEN-LAST:event_jMenuItemConsultarNotaFiscalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuAlterar;
    private javax.swing.JMenuBar jMenuBarMenuPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCadastroCardapio;
    private javax.swing.JMenu jMenuCadastroCardapio1;
    private javax.swing.JMenu jMenuCadastroCardapio2;
    private javax.swing.JMenu jMenuCadastroCardapio3;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenu jMenuDeletar;
    private javax.swing.JMenuItem jMenuDeletarComida;
    private javax.swing.JMenuItem jMenuItemAlterarBebida;
    private javax.swing.JMenuItem jMenuItemAlterarCliente;
    private javax.swing.JMenuItem jMenuItemAlterarComida;
    private javax.swing.JMenuItem jMenuItemAlterarNotaFiscal;
    private javax.swing.JMenuItem jMenuItemAlterarVendedor;
    private javax.swing.JMenuItem jMenuItemCadastrarComida;
    private javax.swing.JMenuItem jMenuItemCadastroBebida;
    private javax.swing.JMenuItem jMenuItemCadastroCliente;
    private javax.swing.JMenuItem jMenuItemCadastroNotaFiscal;
    private javax.swing.JMenuItem jMenuItemCadastroVendedor;
    private javax.swing.JMenuItem jMenuItemConsultarBebida;
    private javax.swing.JMenuItem jMenuItemConsultarCliente;
    private javax.swing.JMenuItem jMenuItemConsultarComida;
    private javax.swing.JMenuItem jMenuItemConsultarNotaFiscal;
    private javax.swing.JMenuItem jMenuItemConsultarVendedor;
    private javax.swing.JMenuItem jMenuItemDeletarBebida;
    private javax.swing.JMenuItem jMenuItemDeletarCliente;
    private javax.swing.JMenuItem jMenuItemDeletarNotaFiscal;
    private javax.swing.JMenuItem jMenuItemDeletarVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator17;
    private javax.swing.JPopupMenu.Separator jSeparator18;
    private javax.swing.JPopupMenu.Separator jSeparator19;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator20;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
