/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Alterar;

import classesBasicas.Cliente;
import metodos.ConvercaoDate;
import static metodos.ConvercaoDate.parseDate;
import classesBasicas.NotaFiscal;
import classesBasicas.Vendedor;
import java.sql.DataTruncation;
import negocio.NegocioCliente;
import negocio.NegocioNotaFiscal;
import negocio.NegocioVendedor;
import java.util.ArrayList;
import java.util.zip.DataFormatException;
import javax.swing.JOptionPane;

/**
 *
 * @author thade
 */
public class AlterarNotaFiscal extends javax.swing.JFrame {

    /**
     * Creates new form AlterarNotaFiscal
     */
    public AlterarNotaFiscal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigoNota = new javax.swing.JTextField();
        jLabelNomeCli = new javax.swing.JLabel();
        jTextFieldCliente = new javax.swing.JTextField();
        jLabelNomeVend = new javax.swing.JLabel();
        jTextFieldVendedor = new javax.swing.JTextField();
        jLabelDataEmissao = new javax.swing.JLabel();
        jTextFieldDataEmissao = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoProcurar = new javax.swing.JTextField();
        jLabelNovosValores = new javax.swing.JLabel();
        jButtonProcurarNota = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jComboBoxNotas = new javax.swing.JComboBox<>();
        jComboBoxClientes = new javax.swing.JComboBox<>();
        jComboBoxVendedores = new javax.swing.JComboBox<>();
        jButtonClientes = new javax.swing.JButton();
        jButtonVendedores = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Nota Fiscal");

        jLabelCodigo.setText("Codigo");

        jTextFieldCodigoNota.setEnabled(false);

        jLabelNomeCli.setText("Cliente");

        jTextFieldCliente.setEnabled(false);
        jTextFieldCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldClienteKeyTyped(evt);
            }
        });

        jLabelNomeVend.setText("Vendedor");

        jTextFieldVendedor.setEnabled(false);
        jTextFieldVendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldVendedorKeyTyped(evt);
            }
        });

        jLabelDataEmissao.setText("Data de emissão");

        jTextFieldDataEmissao.setEnabled(false);

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabelTitulo.setText("Alterar Nota Fiscal");

        jLabel1.setText("Digite o código da Nota que você quer alterar");

        jTextFieldCodigoProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoProcurarKeyTyped(evt);
            }
        });

        jLabelNovosValores.setText("Insira os novos valores aqui");

        jButtonProcurarNota.setText("Selecionar Nota");
        jButtonProcurarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcurarNotaActionPerformed(evt);
            }
        });

        jButtonListar.setText("Listar Notas");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jComboBoxNotas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jComboBoxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jComboBoxVendedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jButtonClientes.setText("Listar Clientes");
        jButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClientesActionPerformed(evt);
            }
        });

        jButtonVendedores.setText("Listar Vendedores");
        jButtonVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVendedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAlterar)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelCodigo)
                                        .addComponent(jLabelNomeCli)
                                        .addComponent(jLabelNomeVend)
                                        .addComponent(jLabelDataEmissao)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                    .addComponent(jTextFieldCliente)
                                    .addComponent(jTextFieldCodigoNota)
                                    .addComponent(jTextFieldDataEmissao))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBoxVendedores, 0, 91, Short.MAX_VALUE)
                                    .addComponent(jComboBoxClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNovosValores)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListar)
                    .addComponent(jButtonProcurarNota))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProcurarNota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListar)
                    .addComponent(jComboBoxNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelNovosValores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodigo)
                    .addComponent(jTextFieldCodigoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeCli)
                    .addComponent(jTextFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClientes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeVend)
                    .addComponent(jTextFieldVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonVendedores))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDataEmissao)
                    .addComponent(jTextFieldDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jButtonAlterar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProcurarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcurarNotaActionPerformed
        NotaFiscal notaFiscal = new NotaFiscal();
        NegocioNotaFiscal nota = new NegocioNotaFiscal();
        jButtonClientesActionPerformed(evt);
        jButtonVendedoresActionPerformed(evt);

        try {
            notaFiscal.setCodigoNota(Integer.parseInt(jComboBoxNotas.getSelectedItem().toString()));
            ArrayList<NotaFiscal> nf = nota.consultarNotaFiscal(notaFiscal);

            for (NotaFiscal notaF : nf) {
                jTextFieldCodigoProcurar.setText(Integer.toString(notaF.getCodigoNota()));
                jTextFieldCodigoNota.setText(Integer.toString(notaF.getCodigoNota()));
                jTextFieldCliente.setText(notaF.getCliente().getNome());
                jTextFieldVendedor.setText(notaF.getVendedor().getNome());
                jTextFieldDataEmissao.setText(ConvercaoDate.parseDate((notaF.getDataEmissao())));
            }
            jTextFieldCliente.setEnabled(true);
            jTextFieldVendedor.setEnabled(true);
            jTextFieldDataEmissao.setEnabled(true);
            jButtonAlterar.setEnabled(true);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um código válido");

        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Insira corretamente o código da nota");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonProcurarNotaActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        NegocioNotaFiscal notaFiscal = new NegocioNotaFiscal();

        jComboBoxNotas.removeAllItems();
        try {
            ArrayList<NotaFiscal> nf = notaFiscal.listarNotaFiscal();
            for (NotaFiscal notaF : nf) {
                jComboBoxNotas.addItem(Integer.toString(notaF.getCodigoNota()));

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jTextFieldCodigoProcurarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProcurarKeyTyped
        NotaFiscal notaFiscal = new NotaFiscal();
        NegocioNotaFiscal notaF = new NegocioNotaFiscal();
        jComboBoxNotas.removeAllItems();

        try {
            notaFiscal.setCodigoNota(Integer.parseInt(jTextFieldCodigoProcurar.getText()));
            ArrayList<NotaFiscal> n = notaF.listarNotaFiscal();

            for (NotaFiscal nota : n) {
                jComboBoxNotas.addItem(Integer.toString(nota.getCodigoNota()));
            }

        } catch (NumberFormatException e) {
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTextFieldCodigoProcurarKeyTyped

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        NotaFiscal notaFiscal = new NotaFiscal();
        NegocioNotaFiscal notaF = new NegocioNotaFiscal();
        NegocioVendedor vend = new NegocioVendedor();
        NegocioCliente cli = new NegocioCliente();

        try {
            notaFiscal.setCodigoNota(Integer.parseInt(jComboBoxNotas.getSelectedItem().toString()));
            notaFiscal.setDataEmissao(parseDate(jTextFieldDataEmissao.getText()));
            notaFiscal.getCliente().setNome(jTextFieldCliente.getText());

            notaFiscal.getCliente().setNome(jComboBoxClientes.getSelectedItem().toString());
            notaFiscal.getVendedor().setNome(jComboBoxVendedores.getSelectedItem().toString());

            ArrayList<Cliente> c = cli.consultarClienteLike(notaFiscal.getCliente());
            ArrayList<Vendedor> v = vend.consultarVendedorLike(notaFiscal.getVendedor());

            for (Cliente cl : c) {
                notaFiscal.getCliente().setCpf(cl.getCpf());
            }
            for (Vendedor ve : v) {
                notaFiscal.getVendedor().setCodigo(ve.getCodigo());
            }

            int escolha = JOptionPane.showConfirmDialog(null, "Deseja alterar a nota fiscal de código: " + notaFiscal.getCodigoNota() + "?");
            if (escolha == 0) {
                notaF.alterarNotaFiscal(notaFiscal);
                JOptionPane.showMessageDialog(null, "Nota Fiscal alterada com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não alterado");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClientesActionPerformed
        NegocioCliente cli = new NegocioCliente();
        jComboBoxClientes.removeAllItems();
        try {
            ArrayList<Cliente> c = cli.listarCliente();
            for (Cliente clientes : c) {
                jComboBoxClientes.addItem(clientes.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonClientesActionPerformed

    private void jButtonVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVendedoresActionPerformed
        NegocioVendedor vend = new NegocioVendedor();
        jComboBoxVendedores.removeAllItems();
        try {
            ArrayList<Vendedor> v = vend.listarVendedor();
            for (Vendedor ven : v) {
                jComboBoxVendedores.addItem(ven.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonVendedoresActionPerformed

    private void jTextFieldClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldClienteKeyTyped
        NotaFiscal notaFiscal = new NotaFiscal();
        NegocioCliente cli = new NegocioCliente();

        jComboBoxClientes.removeAllItems();

        try {
            notaFiscal.getCliente().setNome(jTextFieldCliente.getText());
            ArrayList<Cliente> c = cli.consultarClienteLike(notaFiscal.getCliente());

            for (Cliente clientes : c) {
                jComboBoxClientes.addItem(clientes.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTextFieldClienteKeyTyped

    private void jTextFieldVendedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldVendedorKeyTyped
        NotaFiscal notaf = new NotaFiscal();
        NegocioVendedor vend = new NegocioVendedor();

        jComboBoxVendedores.removeAllItems();

        try {
            notaf.getVendedor().setNome(jTextFieldVendedor.getText());
            ArrayList<Vendedor> v = vend.consultarVendedorLike(notaf.getVendedor());

            for (Vendedor vendedores : v) {
                jComboBoxVendedores.addItem(vendedores.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTextFieldVendedorKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarNotaFiscal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarNotaFiscal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonClientes;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonProcurarNota;
    private javax.swing.JButton jButtonVendedores;
    private javax.swing.JComboBox<String> jComboBoxClientes;
    private javax.swing.JComboBox<String> jComboBoxNotas;
    private javax.swing.JComboBox<String> jComboBoxVendedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelDataEmissao;
    private javax.swing.JLabel jLabelNomeCli;
    private javax.swing.JLabel jLabelNomeVend;
    private javax.swing.JLabel jLabelNovosValores;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCliente;
    private javax.swing.JTextField jTextFieldCodigoNota;
    private javax.swing.JTextField jTextFieldCodigoProcurar;
    private javax.swing.JTextField jTextFieldDataEmissao;
    private javax.swing.JTextField jTextFieldVendedor;
    // End of variables declaration//GEN-END:variables
}
