/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.Alterar;

import classesBasicas.Bebida;
import negocio.NegocioBebida;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author thade
 */
public class AlterarBebida extends javax.swing.JFrame {

    /**
     * Creates new form AlterarBebida
     */
    public AlterarBebida() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelCapacidade = new javax.swing.JLabel();
        jLabelMarca = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCapacidade = new javax.swing.JTextField();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();
        jLabelSelecionar = new javax.swing.JLabel();
        jComboBoxBebidas = new javax.swing.JComboBox<>();
        jLabelNovosValores = new javax.swing.JLabel();
        jTextFieldProcurar = new javax.swing.JTextField();
        jButtonSelecionar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jLabelTipoBebida = new javax.swing.JLabel();
        jTextFieldTipoBebida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alterar Bebida");

        jLabelNome.setText("Nome");

        jLabelCapacidade.setText("Capacidade");

        jLabelMarca.setText("Marca");

        jTextFieldNome.setEnabled(false);

        jTextFieldCapacidade.setEnabled(false);

        jTextFieldMarca.setEnabled(false);

        jLabelTitulo.setText("Alterar Bebida");

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabelSelecionar.setText("Selecione a bebida que você quer alterar");

        jComboBoxBebidas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));

        jLabelNovosValores.setText("Insira os novos valores aqui");

        jTextFieldProcurar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldProcurarKeyTyped(evt);
            }
        });

        jButtonSelecionar.setText("Selecionar");
        jButtonSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarActionPerformed(evt);
            }
        });

        jButtonListar.setText("Listar todos");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jLabelTipoBebida.setText("Tipo Bebida");

        jTextFieldTipoBebida.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelSelecionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxBebidas, 0, 91, Short.MAX_VALUE)
                            .addComponent(jTextFieldProcurar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSelecionar)
                            .addComponent(jButtonListar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNovosValores)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTipoBebida)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addComponent(jLabelNome))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabelCapacidade))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabelMarca))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldCapacidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTipoBebida, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jButtonAlterar)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabelSelecionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSelecionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxBebidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonListar))))
                .addGap(24, 24, 24)
                .addComponent(jLabelNovosValores)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapacidade)
                    .addComponent(jTextFieldCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarca)
                    .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoBebida)
                    .addComponent(jTextFieldTipoBebida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarActionPerformed
        Bebida bebida = new Bebida();
        NegocioBebida com = new NegocioBebida();

        try {
            if (jComboBoxBebidas.getSelectedObjects().length == 0) {
                JOptionPane.showMessageDialog(null, "Digite uma bebida válida");
            } else {
                bebida.setNome(jComboBoxBebidas.getSelectedItem().toString());

                ArrayList<Bebida> b = com.consultarBebidaLike(bebida);
                if (!b.isEmpty()) {
                    for (Bebida beb : b) {
                        jTextFieldNome.setText(beb.getNome());
                        jTextFieldCapacidade.setText(Integer.toString(beb.getCapacidade()));
                        jTextFieldMarca.setText(beb.getMarca());
                        jTextFieldTipoBebida.setText(beb.getTipo());
                        jLabelNovosValores.setText("Insira os novos valores do produto: " + beb.getNome());

                    }
                    jTextFieldNome.setEnabled(true);
                    jTextFieldMarca.setEnabled(true);
                    jTextFieldCapacidade.setEnabled(true);
                    jTextFieldTipoBebida.setEnabled(true);
                    jButtonAlterar.setEnabled(true);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonSelecionarActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        NegocioBebida com = new NegocioBebida();
        jComboBoxBebidas.removeAllItems();
        try {
            ArrayList<Bebida> b = com.listarBebida();
            for (Bebida beb : b) {
                jComboBoxBebidas.addItem(beb.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jTextFieldProcurarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldProcurarKeyTyped
        Bebida bebida = new Bebida();
        NegocioBebida beb = new NegocioBebida();
        jComboBoxBebidas.removeAllItems();

        try {
            bebida.setNome(jTextFieldProcurar.getText());
            ArrayList<Bebida> b = beb.consultarBebidaLike(bebida);

            for (Bebida bebi : b) {
                jComboBoxBebidas.addItem(bebi.getNome());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jTextFieldProcurarKeyTyped

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        Bebida bebida = new Bebida();
        NegocioBebida beb = new NegocioBebida();

        try {
            bebida.setNome(jComboBoxBebidas.getSelectedItem().toString());
            ArrayList<Bebida> b = beb.consultarBebidaLike(bebida);

            for (Bebida bebi : b) {
                bebida.setCodigo(bebi.getCodigo());
            }
            bebida.setNome(jTextFieldNome.getText());
            bebida.setCapacidade(Integer.parseInt(jTextFieldCapacidade.getText()));
            bebida.setMarca(jTextFieldMarca.getText());
            bebida.setTipo(jTextFieldTipoBebida.getText());

            int escolha = JOptionPane.showConfirmDialog(null, "Deseja alterar o produto: " + bebida.getNome() + "?");
            if (escolha == 0) {
                beb.alterarBebida(bebida);
                JOptionPane.showMessageDialog(null, "Produto alterado com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Não alterado");
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Digite apenas números na capacidade");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarBebida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarBebida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonSelecionar;
    private javax.swing.JComboBox<String> jComboBoxBebidas;
    private javax.swing.JLabel jLabelCapacidade;
    private javax.swing.JLabel jLabelMarca;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNovosValores;
    private javax.swing.JLabel jLabelSelecionar;
    private javax.swing.JLabel jLabelTipoBebida;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldCapacidade;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldProcurar;
    private javax.swing.JTextField jTextFieldTipoBebida;
    // End of variables declaration//GEN-END:variables
}
